# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='bluffCaller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bluffCaller', to='game.GamePlayer'),
        ),
    ]
