# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='noAction',
            new_name='no_action',
        ),
    ]
