# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20201012_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametablesnapshot',
            name='lastUser',
        ),
        migrations.AddField(
            model_name='gametablesnapshot',
            name='last_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_user', to='game.GamePlayer'),
        ),
    ]
