# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201012_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametablesnapshot',
            name='bluffCaller',
        ),
        migrations.AddField(
            model_name='gametablesnapshot',
            name='bluff_caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bluff_caller', to='game.GamePlayer'),
        ),
    ]
