# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201012_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametablesnapshot',
            old_name='didSkip',
            new_name='did_skip',
        ),
    ]
