# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201012_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='decks',
            field=models.PositiveIntegerField(default=1, help_text='no of decks in the game from 1-3'),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(help_text='user which is the owner of this game', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False, help_text='tells if game is started or not'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='user who won the game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='cards',
            field=models.CharField(help_text='string of length 156 where 1 is represented by card that user have', max_length=156),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='disconnected',
            field=models.BooleanField(default=True, help_text='tells if player is disconnected'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(help_text='game of which gamePlayer is part of', on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='no_action',
            field=models.PositiveIntegerField(default=0, help_text='no of times no action is performed'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='player_id',
            field=models.PositiveIntegerField(blank=True, help_text='id assigned to a player', null=True),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='bluff_caller',
            field=models.ForeignKey(blank=True, help_text='gameplayer who called bluff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bluff_caller', to='game.GamePlayer'),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='bluff_successful',
            field=models.NullBooleanField(help_text='bluff was successful or not'),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='cards_on_table',
            field=models.CharField(help_text='string of length 156 where 1 is represented by card on table', max_length=156),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='current_set',
            field=models.PositiveIntegerField(blank=True, help_text='current_set from 1-13', null=True),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='current_user',
            field=models.ForeignKey(help_text='gamePlayer instance whose turn is current', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='game.GamePlayer'),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='did_skip',
            field=models.NullBooleanField(help_text='if cureent user skipped his turn'),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='game',
            field=models.ForeignKey(help_text='instance of the game', on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='last_cards',
            field=models.CharField(help_text='string of length 156 which represents last cards that were played', max_length=156),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='last_user',
            field=models.ForeignKey(help_text='Gamplayer instance whose turn was last', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_user', to='game.GamePlayer'),
        ),
    ]
