# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20201012_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametablesnapshot',
            name='current_set',
        ),
        migrations.AddField(
            model_name='gametablesnapshot',
            name='current_rank',
            field=models.PositiveIntegerField(blank=True, help_text='current_rank from 1-13', null=True),
        ),
    ]
