# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20201015_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='cards',
            field=models.CharField(help_text='string of length max_decks*52 where 1 is represented by card that user have', max_length=156),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='cards_on_table',
            field=models.CharField(help_text='string of length max_decks*52 where 1 is represented by card on table', max_length=156),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='current_user',
            field=models.ForeignKey(help_text='GamePlayer instance whose turn is current', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='game.GamePlayer'),
        ),
        migrations.AlterField(
            model_name='gametablesnapshot',
            name='last_cards',
            field=models.CharField(help_text='string of length max_decks*52 which represents last cards that were played', max_length=156),
        ),
    ]
